<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPDHKaRE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPDHKaRE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPDHKaRE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPDHKaRE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPDHKaRE\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'PDHKaRE',
    'container.build_id' => '2081d1c5',
    'container.build_time' => 1545943017,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPDHKaRE');
